In [28]:
import pandas as pd
import numpy as np
import math

import os

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import LSTM, TimeDistributed, ConvLSTM2D

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,roc_auc_score,recall_score,precision_score
from keras import backend as k

In [29]:
data_path = os.getcwd() + "/dataset/total_concentrated.csv"
# features = ["A_F", "A_V", "A_L", "L_F", "L_T", "L_L", "T_F", "T_V", "T_L"]

dataset = pd.read_csv(data_path)
time = list(dataset['time'])
dataframe = dataset[["A_F", "A_V", "A_L", "L_F", "L_V", "L_L", "T_F", "T_V", "T_L"]].values
dataset = dataset[["A_F", "A_V", "A_L", "L_F", "L_V", "L_L", "T_F", "T_V", "T_L", "Action"]].values

window_length = int(1*64)
total_windows = int((len(dataset))/window_length)

In [30]:
dataframe = (dataframe-dataframe.mean())/dataframe.std()

確認每段資料能不能整除64/2, 並輸出不能整除的個數

In [31]:
indices = time
groups = []
group_count = 0
temp = []
lenOfGroup = []
length_count = 0

for i in range(len(indices)):
    if i == (len(indices) - 1):
        temp.append(indices[i])
        length_count = length_count + 1

        groups.append(temp)
        lenOfGroup.append(length_count)
        length_count = 0
        temp = []
        break
    temp.append(indices[i])
    length_count = length_count + 1
    if (indices[i+1] - 20 > indices[i]):
        group_count = group_count + 1

        lenOfGroup.append(length_count)
        length_count = 0

        groups.append(temp)
        temp = []

del temp, indices, group_count, length_count, i

countOfUndivisible = 0
total_windows_with_overlap_train = 0

start_index = 0

stop_Indexs = []
stop_Index = -window_length


for lengths in lenOfGroup:
    stop_Index = stop_Index + lengths
    stop_Indexs.append(stop_Index)
    total_windows_with_overlap_train = total_windows_with_overlap_train + int(float(lengths/window_length)*2 -1)
    
    if lengths % (window_length/2) != 0:
        countOfUndivisible = countOfUndivisible + 1
        print(lengths)

print(countOfUndivisible)
del countOfUndivisible, lengths

0


In [32]:
X = np.empty((total_windows_with_overlap_train, window_length*9))
y = np.empty((total_windows_with_overlap_train, 1))

stop_Index = 0
window_count = 0

for window in range(total_windows_with_overlap_train):
    for i in range(window_length):
        if i == 0:
            y[window] = dataset[int(window_count*window_length), 9]
        
        if int(window_count*window_length)<len(dataset)-window_length-1:
            for data in range(9):
               X[window, i*9 + data] = dataframe[int(window_count*window_length) + i, data]
        if stop_Index < len(stop_Indexs):
            if int(window_count*window_length) == stop_Indexs[stop_Index]:
                window_count = window_count + 0.5
                stop_Index = stop_Index + 1
        if window == total_windows_with_overlap_train-1:
            X[window, i*9 + data] = dataframe[int((window_count-0.5)*window_length) + i, data]
    window_count = window_count + 0.5

In [33]:
from sklearn.model_selection import StratifiedKFold

In [34]:
X, X_test, y, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
unique, counts = np.unique(y, return_counts=True)

class_weight = {0:(1/counts[0])*len(y)/2, 1:(1/counts[1])*len(y)/2, 2:(1/counts[2])*len(y)/2}

In [36]:
skf = StratifiedKFold(n_splits=10, shuffle = True, random_state=42)
skf.get_n_splits(X, y)
print(skf)

StratifiedKFold(n_splits=10, random_state=42, shuffle=True)


In [37]:
def to_3Darray(array):
    arr_3d = np.empty((len(array), window_length, 9))


    arr_3d = np.reshape(array, (len(array), window_length, 9))
    return arr_3d

In [38]:
scores = list()

In [39]:
scores_in_fold = []
losses = []

In [40]:
scores_outside_fold = []

In [41]:
for i, (train_index, val_index) in enumerate(skf.split(X, y)):
    print("==> Fold #%d" % i)
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]

    X_train = to_3Darray(X_train)
    y_train = to_categorical(y_train)

    X_val = to_3Darray(X_val)
    y_val = to_categorical(y_val)


    
    verbose, epochs, batch_size = 0, 50, 64
    n_timesteps, n_features, n_outputs = X_train.shape[1], X_train.shape[2], y_train.shape[1]

    n_steps, n_length = 2, 32
    X_train = X_train.reshape((X_train.shape[0], n_steps, n_length, n_features))
    X_val = X_val.reshape((X_val.shape[0], n_steps, n_length, n_features))


    model = Sequential()
    model.add(TimeDistributed(Conv1D(filters=64, kernel_size=3, activation='relu'),
                            input_shape=(None, n_length, n_features)))
    model.add(TimeDistributed(
        Conv1D(filters=64, kernel_size=3, activation='relu')))
    model.add(TimeDistributed(Dropout(0.5)))
    model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
    model.add(TimeDistributed(Flatten()))
    model.add(LSTM(100))
    model.add(Dropout(0.5))
    hunderdOutput = Dense(100, activation='relu')
    model.add(hunderdOutput)  # feature
    # 試著輸出長度為100的向量(feature) 並絳維 看他的分布有無分開
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy']) #可能可以調weighting
    
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, verbose=verbose, class_weight = class_weight)
    
    loss, accuracy = model.evaluate(X_val, y_val, batch_size=batch_size, verbose=0)
    

    y_pred = (model.predict(X_val) > 0.5).astype("int32")
    y_val = np.argmax(y_val, axis=1)
    y_pred = np.argmax(y_pred, axis=1)

    confus = confusion_matrix(y_val, y_pred, labels=None, sample_weight=None)
    tp = confus[1][1]
    tn = confus[0][0] + confus[0][2] + confus[2][0] + confus[2][2]
    fp = confus[1][0] + confus[1][2]
    fn = confus[0][1] + confus[2][1]

    precision = (tp/(tp + fp))*100
    recall =  (tp / (tp + fn))*100   #sensitivity
    F1_score = ((2*tp) / (2*tp + fp + fn))*100

    score = accuracy
    losses.append(loss)
    
    score = score * 100.0
    scores_in_fold.append(score)
    
    print('Loss: %.3f%% Accuracy: %.3f%% ' % (loss, score))
    print('precision: %.3f%% recall: %.3f%% F1 score: %.3f%%' % (precision, recall, F1_score))
    # print(confus)


    
    '''score = evaluate_model(X_train, y_train, X_val, y_val)
    score = score * 100.0
    print(score)
    scores.append(score)'''

    

==> Fold #0
Loss: 0.316% Accuracy: 87.777% 
precision: 86.905% recall: 53.808% F1 score: 66.464%
==> Fold #1
Loss: 0.373% Accuracy: 85.563% 
precision: 90.873% recall: 47.808% F1 score: 62.654%
==> Fold #2
Loss: 0.265% Accuracy: 90.594% 
precision: 89.286% recall: 60.322% F1 score: 72.000%
==> Fold #3
Loss: 0.294% Accuracy: 88.475% 
precision: 82.143% recall: 54.762% F1 score: 65.714%
==> Fold #4
Loss: 0.592% Accuracy: 73.679% 
precision: 94.048% recall: 33.193% F1 score: 49.068%
==> Fold #5
Loss: 0.272% Accuracy: 89.683% 
precision: 84.524% recall: 58.197% F1 score: 68.932%
==> Fold #6
Loss: 0.368% Accuracy: 86.059% 
precision: 88.845% recall: 49.556% F1 score: 63.623%
==> Fold #7
Loss: 0.315% Accuracy: 88.374% 
precision: 86.454% recall: 54.937% F1 score: 67.183%
==> Fold #8
Loss: 0.348% Accuracy: 87.116% 
precision: 84.462% recall: 51.084% F1 score: 63.664%
==> Fold #9
Loss: 0.335% Accuracy: 87.871% 
precision: 86.056% recall: 52.555% F1 score: 65.257%


In [42]:
layerIndex = 7
func = k.function([model.get_layer(index=0).input], model.get_layer(index=layerIndex).output)
layerOutput = func([X_val])

In [43]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

principalComponents = pca.fit_transform(layerOutput)

principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])
y_val = pd.DataFrame(data = y_val, columns=['targets'])

In [44]:
finalDF = pd.concat([principalDf, y_val], axis=1, ignore_index=True)

In [45]:
# import matplotlib.pyplot as plt

# fig = plt.figure(figsize = (8,8))
# ax = fig.add_subplot(1,1,1) 
# ax.set_xlabel('Principal Component 1', fontsize = 15)
# ax.set_ylabel('Principal Component 2', fontsize = 15)
# ax.set_title('2 component PCA', fontsize = 20)
# targets = [0, 1, 2]
# colors = ['r', 'g', 'b']
# for target, color in zip(targets,colors):
#     indicesToKeep = finalDF[2] == target
#     ax.scatter(finalDF.loc[indicesToKeep, 0]
#                , finalDF.loc[indicesToKeep, 1]
#                , c = color
#                , s = 50)
# ax.legend(targets)
# ax.grid()

In [46]:
m, s = np.mean(scores_in_fold), np.std(scores_in_fold)
print('Accuracy: %.3f%% (+/-%.3f)' % (m, s))

Accuracy: 86.519% (+/-4.513)


In [47]:
X_test = to_3Darray(X_test)
#y_test = to_categorical(y_test)
X_test = X_test.reshape((X_test.shape[0], n_steps, n_length, n_features))


# loss, accuracy = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=0)


In [48]:
y_test = to_categorical(y_test)
y_pred = (model.predict(X_test) > 0.5).astype("int32")
y_test = np.argmax(y_test, axis=1)
y_pred = np.argmax(y_pred, axis=1)

confus = confusion_matrix(y_test, y_pred, labels=None, sample_weight=None)

In [49]:
print(confus)

[[3881  415   13]
 [  70  533    8]
 [  11   35    3]]


In [50]:
accuracy = accuracy_score(y_test, y_pred)*100

In [51]:
accuracy = accuracy
print('Accuracy: %.3f%% ' % (accuracy))

Accuracy: 88.891% 


In [52]:
from keras.models import load_model

In [53]:
model.save('my_model.h5')